{
 "title": "CLOUD",
 "description": "dash",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"apps\",deployment=\"quote-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(sum by (pod) (rate(http_server_requests_seconds_count{namespace=\"apps\",pod=~\"quote-app-.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=\"apps\",pod=~\"quote-app-[a-f0-9]+-[a-z0-9]+\"}) /\n  sum(kube_pod_container_resource_requests{namespace=\"apps\",container=\"quote-app\",resource=\"memory\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"apps\",pod=~\"quote-app-[a-f0-9]+-[a-z0-9]+\"}[1m])) /\n  sum(kube_pod_container_resource_requests{namespace=\"apps\",container=\"quote-app\",resource=\"cpu\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}