replicaCount: 1

image:
  repository: xfarkasp/mudro-dna-be
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

resources: {}

startupProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 5
  failureThreshold: 30
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  periodSeconds: 10
  failureThreshold: 3
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  periodSeconds: 5
  failureThreshold: 3
startupProbe:
  httpGet:
    path: /actuator/health
    port: http
  periodSeconds: 5
  failureThreshold: 60

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

mongodb:
  image:
    tag: "latest"
  auth:
    rootUser: root
    rootPassword: secret
    usernames:
      - root
    passwords:
      - secret
    databases:
      - quote

app:
  mongodb:
    host: quote-app-mongodb
    port: 27017
    database: quote
    username: root
    password: secret
    authDb: admin